### ISSUE TITLE
Open loopback device as RW

### ISSUE THREAD

**Issue by k-jingyang** [paultag/go-loopback#1]
Hey @paultag, thanks for opening this library up. :smile:  I came across this project while using it to mount a filesystem image with the intention of modifying its contents.

I faced permission issues and realised that it was because the loopback is opened as read only (see below).

```go
// loopback.go
func NextLoopDevice() (*os.File, error) {
	loopInt, err := nextUnallocatedLoop()
	if err != nil {
		return nil, err
	}
        // open loopback device as read only
	return os.Open(fmt.Sprintf("/dev/loop%d", loopInt))
}

// my-code.go
func main() {
	_, unmount, err := loopback.MountImage(imageFile, target, "ext4", 0, "") // permission denied
        _, unmount, err := loopback.MountImage(imageFile, target, "ext4", syscall.MS_RDONLY, "") // this will work
        ... 
}
```

Is it possible to update the library's API to let callers have the flexibility of opening loopback with read write?

**Comment by paultag** [comment]
@k-jingyang Thank you for this report! What a great call. I've pushed an update that will open `/dev/loop%d` as `O_RDWR` using `OpenFile`, which works locally. Let me know if there's any more issues you find! I've pushed that fix up as `v0.1.4`
